services:
  framework-express:  # ← изменил имя
    build:
      context: .
      dockerfile: Dockerfile.express
    ports:
      - "3000:3000"
    environment:
      - DATABASE_NAME=anekdot_test
    networks:
      - test-network

  framework-fastify:  # ← изменил имя
    build:
      context: .
      dockerfile: Dockerfile.fastify
    ports:
      - "3001:3000"
    environment:
      - DATABASE_NAME=anekdot_test
    networks:
      - test-network

  benchmark:
    build:
      context: .
      dockerfile: Dockerfile.benchmark
    networks:
      - test-network
    volumes:
      - ./results:/app/results

networks:
  test-network:
    driver: bridge