services:
  framework-express:
    build: ./framework-express
    ports:
      - "3000:3000"
    networks:
      - test-network

  framework-fastify:
    build: ./framework-fastify
    ports:
      - "3001:3000"
    networks:
      - test-network

  benchmark:
    build: ./benchmark
    networks:
      - test-network
    depends_on:
      - framework-express
      - framework-fastify

networks:
  test-network:
    driver: bridge