global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'express-app'
    static_configs:
      - targets: ['framework-express:3000']

  - job_name: 'fastify-app'
    static_configs:
      - targets: ['framework-fastify:3000']